import express from "express";
import cors from "cors";

const app = express();

app.use(express.json());
app.use(cors());

//상품 구매하기
app.post("/products/buy", (req, res) => {
  //1. 가진 돈을 검증하는 코드
  //...
  //...
  //...
  //...
  //2. 판매여부를 검증하는 코드 (중고 거래)
  //...
  //...
  //...
  //...
  //3. 상품 구매 코드
  // if(돈있음 && !판매완료) {
  //   res.send("상품 구매 완료!!")
  // }
  //...
  //...
  //...
});

//상품 환불하기
app.post("/products/refund", (req, res) => {
  //1. 판매여부를 검증하는 코드 (중고 거래)
  //...
  //...
  //...
  //...
  //2. 상품을 환불하는 코드
  //if(판매완료) {
  //   res.status(200).send("상품 환불 완료!!");
  // }
});

app.listen(3000, () => {
  console.log("Server On!!!! Linsten port 3000!!!");
});
