version: "3.7"

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server.js:/myfolder/server.js
      - ./email.js:/myfolder/email
    ports:
      - 3000:3000

  my-database:
    image: mongo:5
    ports:
      - 27017:27017
